### ISSUE TITLE
Using promises

### ISSUE THREAD

**Issue by vgoloviznin** [Receiptful/node-bigcommerce#11]
Hello! 

Are you going to add promise support in foreseeable future? 

I would also suggest adding support to usage of work 'authorize' to 'authorise'. I'm used to using 'authorize', though both variants are possible :)

**Comment by dlebech** [comment]
Hi @vgoloviznin sorry for the late reply. I'm adding promises now.

Regarding the naming of functions, if this is an important issue for you, could you perhaps open a separate issue for this? Thanks :smile:

**Comment by dlebech** [comment]
@vgoloviznin This has been published as part of version 2.0.0. Notice a potentially breaking change is that `checkRequirements` have been removed and the checks have been moved to [`request`](https://github.com/Receiptful/node-bigcommerce/blob/2.0.0/lib/bigcommerce.js#L160-L166) instead.
