### ISSUE TITLE
Adding support to 'authorize' naming

### ISSUE THREAD

**Issue by vgoloviznin** [Receiptful/node-bigcommerce#13]
As mentioned here: https://github.com/Receiptful/node-bigcommerce/issues/11 it could be cool to add 'authorize' function names as a lot of libraries are doing that and some developers are used to this sort of naming :)

**Comment by dlebech** [comment]
Thanks, I'm adding this now.

**Comment by dlebech** [comment]
@vgoloviznin This has been published as part of version 2.0.0
