### ISSUE TITLE
Basic Auth

### ISSUE THREAD

**Issue by Peteywiggin** [Receiptful/node-bigcommerce#17]
Is there a way to just do Basic Auth with this, or is this OAuth only? I am new to this so forgive my ignorance, but I am trying to test this using a get request:

`var BigCommerce = require('node-bigcommerce');

var bigCommerce = new BigCommerce({
  clientId: '128ecf542a35ac5270a87dc740918404'
  accessToken: '9df3b01c60df20d13843841ff0d4482c',
  responseType: 'json'
});

bigCommerce.get('/products', function(err, data, response){
  // Catch any errors, or handle the data returned
  // The response object is passed back for convenience
});`

However I am getting an error saying I need the store hash

**Comment by burimshala** [comment]
You have to pass to the config object the store hash eg : 

{
storeHash: 'fa0p0g1',
clientId: '128ecf542a35ac5270a87dc740918404'
accessToken: '9df3b01c60df20d13843841ff0d4482c',
responseType: 'json'
}

The easiest place to find your store hash is in the store URL when you login on your backend.

**Comment by dlebech** [comment]
Sorry for the late reply @Peteywiggin ! @burimshala is right that you need the store hash as well as the `clientId` and `accessToken`. At Receiptful, we use the library like this:
```
new BigCommerce({
  logLevel: 'error',
  clientId: config.bigCommerce.clientId,
  secret: config.bigCommerce.secret,
  responseType: 'json',
  accessToken: userToken,
  storeHash: userStoreHash,
  failOnLimitReached: true
});
```
Regarding oauth vs basic auth. The library only supports oauth authentication. The headers for this are set here: https://github.com/Receiptful/node-bigcommerce/blob/master/lib/bigcommerce.js#L147-L151

**Comment by Peteywiggin** [comment]
Thank you for the reply @dlebech @burimshala! I think this is where I am getting confused, I see on the documentation where to find the store hash (in the backend of the store when I log in) However since we switched to a dedicated SSL this is below and I am still getting the error:

`https://www.mystore.com/manage/legacy-dashboard`

just to be clear, wouldnt my clientId and accessToken be the info in the Legacy API Settings?

**Comment by dlebech** [comment]
I'm not completely sure I follow what you are trying to do? Are you trying to use the library to call your own store directly without a BigCommerce app? The `clientId` used by the library is the `clientId` of a BigCommerce app. The `accessToken` is acquired when an app is installed. As such, the library cannot currently be used without an app. If you want to make it work, you have to create a private or public app and access your data through that app using OAuth (Notice that Basic Authentication seems to be [deprecated by BigCommerce](https://developer.bigcommerce.com/api/guides/oauth-transition)).

So I think you can't immediately access the API with data that you can find on your store dashboard. You need to create an app and authenticate it via OAuth.

Let me know if I misunderstood question :-)

**Comment by Peteywiggin** [comment]
Thanks @dlebech, that seems to be the issue, thanks for the explanation. It looks like I need to wait for approval before I can get my keys, hopefully that will happen soon. Thanks for all your help!
